export const API_CLEAN = "https://ecommerce-hw-project.herokuapp.com"
export const API = "https://ecommerce-hw-project.herokuapp.com/products"
export const API_STORE_MEN="https://ecommerce-hw-project.herokuapp.com/products/category/men"
export const API_STORE_WOMEN="https://ecommerce-hw-project.herokuapp.com/products/category/women"
export const API_STORE_ELECTRONICS="https://ecommerce-hw-project.herokuapp.com/products/category/electronics"
export const API_STORE_JEWELRY="https://ecommerce-hw-project.herokuapp.com/products/category/jewelry"

export const API_LOCAL_CLEAN = "http://localhost:5000"
export const API_LOCAL = "http://localhost:5000/products"
export const API_LOCAL_STORE_MEN = "http://localhost:5000/products/category/men"
export const API_LOCAL_STORE_WOMEN = "http://localhost:5000/products/category/women"
export const API_LOCAL_STORE_ELECTRONICS = "http://localhost:5000/products/category/electronics"
export const API_LOCAL_STORE_JEWELRY = "http://localhost:5000/products/category/jewelry"